Fix SyntaxError: remove duplicate global addon_dir declaration
The init_ui method had two global addon_dir declarations:
- Line 7330: global addon_dir, icon_path (correct)
- Line 7504: global addon_dir (duplicate, incorrect)

Python doesn't allow using a variable and then re-declaring it as
global in the same scope. Removed the duplicate declaration at 7504.

This fixes the error:
SyntaxError: name 'addon_dir' is used prior to global declaration